// Random Image
export const RANDOM_IMAGE = 'RANDOM_IMAGE';
export const RANDOM_IMAGE_SUCCESS = 'RANDOM_IMAGE_SUCCESS';
export const RANDOM_IMAGE_FAILURE = 'RANDOM_IMAGE_FAILURE';

// By Breed
export const BY_BREED = 'BY_BREED';
export const BY_BREED_SUCCESS = 'BY_BREED_SUCCESS';
export const BY_BREED_FAILURE = 'BY_BREED_FAILURE';

// Browse Breed
export const BROWSE_BREED = 'BROWSE_BREED';
export const BROWSE_BREED_SUCCESS = 'BROWSE_BREED_SUCCESS';
export const BROWSE_BREED_FAILURE = 'BROWSE_BREED_FAILURE';

// List Of Breed
export const LIST_OF_BREED = 'LIST_OF_BREED';
export const LIST_OF_BREED_SUCCESS = 'LIST_OF_BREED_SUCCESS';
export const LIST_OF_BREED_FAILURE = 'LIST_OF_BREED_FAILURE';

//user details for class did update
export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';



